# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-Authentication-Driver-CDBI
version:      0.02
version_from: lib/CGI/Application/Plugin/Authentication/Driver/CDBI.pm
installdirs:  site
requires:
    CGI::Application::Plugin::Authentication: 0.06
    Class::DBI:                    0
    DBD::SQLite:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
